apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::981087045439:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1UZS0U6NKPGTJ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::981087045439:role/UdacityAppFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-16T14:15:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "6392"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 5ac278d6-edd6-4419-9c98-bc89d5b5dff5
