apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::981087045439:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-CQVWTQFMZU7G
      username: system:node:{{EC2PrivateDNSName}}
    - groups
      - system:masters
      rolearn: arn:aws:iam::981087045439:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-16T06:31:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1594"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: baa98f16-c838-4b38-ad6a-8ecdb92eed6c
